version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: travel-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Travel123!
      POSTGRES_DB: travelagency
    ports:
      - "5433:5432"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
